---
version: "3.7"

services:
  app:
    image: thesheriff/thesheriff
    build:
      dockerfile: Dockerfile.thesheriff
      context: .
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      DB_HOST: db
      DB_NAME: thesheriffdb
      DB_USER: sheriff
      DB_PASSWD: sh3r1ff
  db:
    image: mariadb:10.4.10
    environment:
      MYSQL_ROOT_PASSWORD: s3cr3t
      MYSQL_DATABASE: thesheriffdb
      MYSQL_USER: sheriff
      MYSQL_PASSWORD: sh3r1ff
