---
version: "3.7"

services:
  app:
    image: thesheriff/thesheriff
    build:
      dockerfile: Dockerfile.thesheriff
      context: .
    ports:
      - 5000:5000
    environment:
      DATABASE_URI: mysql+pymysql://sheriff:sh3r1ff@db/thesheriffdb
    depends_on:
      - "db"
  db:
    image: mariadb:10.4.10
    environment:
      MYSQL_ROOT_PASSWORD: s3cr3t
      MYSQL_DATABASE: thesheriffdb
      MYSQL_USER: sheriff
      MYSQL_PASSWORD: sh3r1ff
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10